name: examples
sort_one_hop_by_read_time: False
rank_two_hop_by_common_clicks: False
size: ebnerd_demo
root_path: ${oc.env:GERL}/data/${dataset.size}/${dataset.name}
result_path: ${oc.env:GERL}/data/${dataset.size}/result/
train: ${dataset.root_path}/training_examples.tsv
valid_name: eval_examples.tsv
valid: ${dataset.root_path}/${dataset.valid_name}
valid_sample: ${dataset.root_path}/eval_examples.sample.tsv
test: ${dataset.root_path}/test_examples2
vocab_subdir: data/${dataset.size}/vocabs
user_vocab: ${oc.env:GERL}/${dataset.vocab_subdir}/userid_vocab.bin
word_vocab: ${oc.env:GERL}/${dataset.vocab_subdir}/word_vocab.bin
word_embedding: ${oc.env:GERL}/${dataset.vocab_subdir}/word_embeddings.npy
doc_emb_kind: facebook_roberta
doc_embedding: ${oc.env:GERL}/${dataset.vocab_subdir}/doc_embeddings_${dataset.doc_emb_kind}.bin.npy
img_embedding: ${oc.env:GERL}/${dataset.vocab_subdir}/img_embeddings.bin.npy
title_embedding: ${oc.env:GERL}/data/${dataset.size}/news_title.npy
max_news_len: 30
max_user_one_hop: 50
max_user_two_hop: 15
max_news_two_hop: 15
user_count: 900000
news_count: 140000
train_split_cnt: 40
valid_split_cnt: 4
test_split_name: p0
